version: '3'
services:

  db:
    image: postgres:11.2
    environment:
      POSTGRES_PASSWORD: N7wBrnQK
      POSTGRES_USER: registration
      POSTGRES_DB: ru_invest
    networks:
      - net
    ports:
      - "6543:5432"
    volumes:
      # https://github.com/docker-library/postgres/blob/master/docker-entrypoint.sh#L145
      - ./nn_invest/sql/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    restart: on-failure

  rest.ru:
    image: invest:1.1
    environment:
      HTTP_PORT: 80
      HTTP_HOST: 0.0.0.0
      APP_BUILD: dev
      POSTGRES_PASSWORD: N7wBrnQK
      POSTGRES_USER: registration
      POSTGRES_DB: ru_invest
      POSTGRES_DB_EN: en_invest
      POSTGRES_PORT: 5432
      #POSTGRES_HOST: 212.109.223.229
      POSTGRES_HOST: db

      MAIL_ADMIN: site116@gmail.com
      MAIL_KRNO: krno@invest.kreml.nnov.ru
      MAIL_SOVET: sovetstrateg@minec.kreml.nnov.ru
      MAIL_TEBEKIN: tebekin@invest.kreml.nnov.ru
      MAIL_YASHIN: yashin@invest.kreml.nnov.ru
      MAIL_USER_NAME: webinvestnn@yandex.ru
      MAIL_PASSWORD: NN2020inv
      MAIL_SERVER: smtp.yandex.ru
      MAIL_PORT: 25

    command:  ./wait-for-it.sh db:5432 -- go run main.go web
    restart: on-failure
    volumes:
      - ./nn_invest/:/code
    ports:
      - "8889:80"
    depends_on:
      - db
    networks:
      - net

volumes:
  tmp:

networks:
  net:
    driver: bridge
